on:
  schedule:
    - cron: "*/15  * * * *"
  push:
    branches: main

jobs:
  render:
    name: Update CRAN packages number
    runs-on: ubuntu-latest
    container: rocker/verse:4.2.0
    steps:
      - uses: actions/checkout@v2

      - name: Scrape the data
        run: |
          Rscript -e 'install.packages("cranology", repos = c("https://thinkr-open.r-universe.dev", getOption("repos")), dependencies = TRUE)'
          Rscript script.R

      - name: Trust directory
        # cf: https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory /__w/cranology-data/cranology-data

      - name: Commit results
        run: |
          git add -A
          git commit -m 'Update CRAN packages number' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
